### ISSUE TITLE
nix module: error: unsupported argument 'submodules' to 'fetchGit', at /nix/store/9i8226p09g7cvih4lf24rysyx1qkxka8-source/lib/downloadCargoPackageFromGit.nix:18:5

### ISSUE THREAD

**Issue by bbigras** [zhaofengli/attic#11]
I'm using:

```nix
{
  imports = [
    "${(import ./nix/sources.nix).attic}/nixos/atticd.nix"
  ];

  services.atticd = {
    enable = true;
    credentialsFile = config.sops.secrets.attic.path;
    settings = {
      database = {
        url = "postgresql://attic@127.0.0.1/attic";
      };

      storage = {
        type = "local";
        path = "/mnt/attic/storage";
      };

      # useFlakeCompatOverlay = false;
    };
  };
}
```

```
[bbigras2@nixos:/etc/nixos]$ sudo nixos-rebuild build
building Nix...
building the system configuration...
error: unsupported argument 'submodules' to 'fetchGit', at /nix/store/9i8226p09g7cvih4lf24rysyx1qkxka8-source/lib/downloadCargoPackageFromGit.nix:18:5
(use '--show-trace' to show detailed location information)
```

nix-info (I'm still on nixos-21.11 but going to update soon):

 - system: `"x86_64-linux"`
 - host os: `Linux 5.10.126, NixOS, 21.11 (Porcupine)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.16`
 - channels(root): `"nixos-21.11.337975.eabc3821918"`
 - channels(bbigras): `"home-manager-20.09"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`

**Comment by zhaofengli** [comment]
Looks like Nix 2.3 doesn't support the `submodules` argument in `fetchGit` used by [crane](https://github.com/ipetkov/crane). If you don't want to or can't upgrade, you can probably use [the alternative package expression](https://github.com/zhaofengli/attic/blob/main/package.nix) that doesn't use crane for building.

Also `path = "/mnt/attic/storage";` may be problematic since the systemd service is configured with `DynamicUser = true;`. When starting the service, systemd automatically changes the ownership of `/var/lib/atticd` so it works but it's not the case for `/mnt/attic/storage`. I recommend bind-mounting the directory to `/var/lib/private/atticd` to there is less fiddling.

**Comment by bbigras** [comment]
> Looks like Nix 2.3 doesn't support the submodules argument in fetchGit used by [crane](https://github.com/ipetkov/crane).

You are right. I upgraded and it's fine now.

> I recommend bind-mounting the directory to /var/lib/private/atticd so there is less fiddling.

Does it absolutely need to be a bind mount? I'm trying to use a CIFS mount and I don't seem able to bind mount a CIFS directly. Maybe I'm doing something wrong.

**Comment by zhaofengli** [comment]
I think you can also mount it directly under `/var/lib/private/atticd`.

**Comment by bbigras** [comment]
I tried, but it was mounted as root. I guess I can't mount with an UID when using `DynamicUser = true;`.

Does the mount need to happen before the service starts? I'm not sure, but I might have seen that the right permission is set when the service starts.

**Comment by zhaofengli** [comment]
Yeah, that's a bit tricky. Maybe the easiest way is to override the systemd service to use a static user with a fixed UID instead of `DynamicUser`. To make this use case less painful, I'll probably [allocate a static UID/GID](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/misc/ids.nix) when this is upstreamed to nixpkgs.

**Comment by bbigras** [comment]
I modified the nix module to use a system user and also removed  `ProtectSystem = "strict";` and it works :tada: 

Thank you very much!
