### ISSUE TITLE
Long time to build the attic-client

### ISSUE THREAD

**Issue by drestrepom** [zhaofengli/attic#30]
I am importing the package and extracting the attic-client attribute but all attic components are built.

This is the code associated with the import and use of attic-client: https://github.com/fluidattacks/makes/compare/main...drestrepom:makes:main#diff-ecdfd02b8e24dc35996c02b7530266eb6fe5e03239e760490f2839d556c55f06R9

What could be the most optimal way to import it?

![2023-02-21_20-17](https://user-images.githubusercontent.com/36453706/220495866-1616bd24-61a6-4914-93f7-3f5c471203c6.png)

**Comment by zhaofengli** [comment]
Glad to see people using Attic! This can be tricky until Attic is added to nixpkgs and cached by `cache.nixos.org`, which is happening soon with the first stable release. I would advise downstream projects to hold off until the release occurs, especially since [a rename](https://github.com/zhaofengli/attic/issues/2) may be happening.

See also https://github.com/zhaofengli/attic/issues/20

**Comment by drestrepom** [comment]
At my job we use nix-based containers to run the CI/CD jobs. These jobs are built with an own framework called [Makes](https://github.com/fluidattacks/makes), this tool makes it easier to configure the environment.

We used cachix as the main cache provider, add attic as an additional cache provider for the tool, so jobs would have a local cache and avoid downloading binaries from the internet, but the difference in time that we save using attic is not worth deploying a cache locally. In addition, the upload of the binaries to the attic server is quite slow compared to cachix.
